language: python
python:
  #- "3.2"
  #- "3.3"
  #- "3.4"
  - "3.5"
  #- "nightly"

cache: pip

install:
  - pip install -r ci/requirements.txt

script:
  - flake8 migrate/ setup.py

deploy:
  provider: pypi
  user: and800
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    branch: "0.x"
    python: "3.5"
